annotations:
  loadbalancer.ovhcloud.com/class: "octavia"
  loadbalancer.ovhcloud.com/flavor: "small"
  service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
  loadbalancer.openstack.org/subnet-id: ${private_lb_subnet_id}
labels:
  istio: ${gw_selector}
service:
    ports:
    - name: otlp
      port: 4317
      protocol: TCP
      targetPort: 4317
